apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-yaml
  name: test-yaml
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-yaml
  template:
    metadata:
      labels:
        app: test-yaml
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
         # command: ["/bin/bash", "-c"]
         # args: ["sleep 5; exit 1"]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
